---
items:
  - { name: ansible }
  - { name: colima }
  - { name: colordiff }
  - { name: docker }
  - { name: docker-compose }
  - { name: elixir }
  - { name: ghq }
  - { name: git }
  - { name: harelba/q/q }
  - { name: htop }
  - { name: jq }
  - { name: lefthook }
  - { name: marp-cli }
  - { name: nkf }
  - { name: peco }
  - { name: tmux }
  - { name: tree }
  - { name: wget }
  - { name: xz }
  - { name: yq }
  - { name: zsh-completion }
